root = "."  # Корневая директория проекта (где искать файлы)
tmp_dir = "tmp"  # Временная директория где Air будет хранить временные файлы

[build]  # Настройки сборки
  bin = "main"  # Имя бинарного файла который будет создан после сборки
  cmd = "go build -o {{.Output}} {{.Input}}"  # Команда для сборки проекта
  exclude = ["tmp/*", "client/*"]  # Директории которые НЕ отслеживать на изменения
  include = ["**/*.go"]  # Шаблоны файлов которые отслеживать на изменения
  ignore = ["tmp/*"]  # Файлы/директории при изменении которых НЕ перезапускать сборку