# docker-compose.yml
services:
  postgres:
    image: postgres:15
    container_name: dailytasks_db
    environment:
      POSTGRES_DB: dailytasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # ← ВНЕШНИЙ порт 5433, ВНУТРЕННИЙ 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: